---
- name: Setting up zabbix agent on windows
  hosts: win
  vars:
    zabbix_install_path: C:\zabbix-agent
    zabbix_bin_path: C:\zabbix-agent\bin
    zabbix_conf_path: C:\zabbix-agent\conf
  tasks:
    - name: Create zabbix directory structure
      win_file:
        path: "{{ zabbix_install_path }}"
        state: directory
    - name: Download zabbix agent
      win_get_url:
        url: https://www.zabbix.com/downloads/5.2.1/zabbix_agent-5.2.1-windows-amd64.zip
        dest: '{{ zabbix_install_path }}\zabbix_agent-5.2.1-windows-amd64.zip'
    - name: Unzip zabbix agent archieve file
      win_unzip:
        src: '{{ zabbix_install_path }}\zabbix_agent-5.2.1-windows-amd64.zip'
        dest: "{{ zabbix_install_path }}"
        delete_archive: yes
    # update the zabbix configuration file
    - name: Set server ip address
      lineinfile:
        path: '{{ zabbix_conf_path }}\zabbix_agentd.conf'
        regexp: "Server=127.0.0.1"
        line: Server="YOUR SERVER IP"
    - name: Set server active ip address
      lineinfile:
        path: '{{ zabbix_conf_path }}\zabbix_agentd.conf'
        regexp: "ServerActive=127.0.0.1"
        line: ServerActive="YOUR SERVER IP"
    - name: Set hostname
      lineinfile:
        path: '{{ zabbix_conf_path }}\zabbix_agentd.conf'
        regexp: "Hostname=Zabbix server"
        line: Hostname='{{ansible_hostname}}'
    - name: Register zabbix agent Service
      win_command: '{{ zabbix_bin_path }}\zabbix_agentd.exe --config {{ zabbix_conf_path }}\zabbix_agentd.conf --install'
      register: zabbix_windows_install
    - name: " Set service startup mode to auto and ensure it is started"
      win_service:
        name: Zabbix Agent
        start_mode: auto
        state: started
